class AppStrings {
  static const String noRouteFound = "no_route_found";
  static const String onboardingTitlePage_1 = "on_boarding_title1";
  static const String onboardingTitlePage_2 = "on_boarding_title2";
  static const String onboardingTitlePage_3 = "on_boarding_title3";
  static const String onboardingDescPage_1 = "on_boarding_desc1";
  static const String onboardingDescPage_2 = "on_boarding_desc2";
  static const String onboardingDescPage_3 = "on_boarding_desc3";
  static const String authTypeScreenTitle = "auth_type_screen_title";
  static const String createAccount = "create_account";
  static const String createNewAccount = "create_new_account";
  static const String welcomeBadk = "welcome_badk";
  static const String signIn = "sign_in";
  static const String signUp = "sign_up";
  static const String fullName = "full_name";
  static const String email = "email";
  static const String password = "password";
  static const String haveAccoun = "have_accoun";
  static const String forgetPassword = "forget_password";
  static const String loading = "loading";
  static const String ok = "ok";
  static const String retryAgain = "retry_again";
  static const String success = "success";
  static const String emailInvalid = "email_invalid";
  static const String passwordInvalid = "password_invalid";
  static const String nameInvalid = "name_invalid";
  static const String hello = "hello";
  static const String searchTextField = "search_text_field";
  static const String search = "search";
  static const String addHotelToFav = "add_hotel_to_fav";
  static const String errorChangingHotelFavState =
      "error_changing_hotel_fav_state";
  static const String minPrice = "min_price";
  static const String maxPrice = "max_price";
  static const String cheapestPrice = "cheapest_price";
  static const String address = "address";
  static const String showLocation = "show_location";
  static const String distance = "distance";
  static const String changeLanguage = "change-language";
  static const String darkMode = "dark-mode";
  static const String lightMode = "light-mode";
  static const String share = "share";
  static const String arabic = "arabic";
  static const String english = "english";
  static const String logout = "logout";

  //! Error Handler
  static const String badRequestError = "bad_request_error";
  static const String forbiddenError = "forbidden_error";
  static const String unauthorizedError = "unauthorized_error";
  static const String notFoundError = "not_found_error";
  static const String conflictError = "conflict_error";
  static const String internalServerError = "internal_server_error";
  static const String unknownError = "unknown_error";
  static const String timeoutError = "timeout_error";
  static const String defaultError = "default_error";
  static const String cacheError = "cache_error";
  static const String noInternetError = "no_internet_error";
}
