name: hotel_booking
description: A new Flutter project.

publish_to: "none"

version: 1.0.4+6

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.0.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  firebase_core: ^2.7.0
  firebase_dynamic_links: ^5.0.15
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^5.0.7
  flutter_phoenix: ^1.0.0
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.2
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.1.6
  google_sign_in: ^6.0.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lottie: ^2.2.0
  mocktail: ^0.3.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.2
  retrofit: ^4.0.1
  rxdart: ^0.27.3
  share: ^2.0.4
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/hotel.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.svg
    - assets/images/booking.svg
    - assets/images/city.svg
    - assets/images/hotel.svg
    - assets/images/person.svg
    - assets/images/space.svg
    - assets/images/travel.svg
    - assets/images/empty.json
    - assets/images/error.json
    - assets/images/loading.json
    - assets/images/success.json
    - assets/translations/ar-EG.json
    - assets/translations/en-US.json
