name: hotel_booking
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  firebase_core: ^1.17.1
  firebase_dynamic_links: ^2.0.6
  firebase_messaging: ^11.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^4.3.4
  flutter_phoenix: ^1.0.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  geolocator: ^8.2.1
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  google_maps_flutter: ^2.1.6
  google_sign_in: ^5.3.2
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lottie: ^1.3.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.2
  retrofit: ^3.0.1+1
  rxdart: ^0.27.3
  share: ^2.0.4
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.svg
    - assets/images/booking.svg
    - assets/images/city.svg
    - assets/images/hotel.svg
    - assets/images/person.svg
    - assets/images/space.svg
    - assets/images/travel.svg
    - assets/images/empty.json
    - assets/images/error.json
    - assets/images/loading.json
    - assets/images/success.json
    - assets/translations/ar-EG.json
    - assets/translations/en-US.json
