// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ke-qblQM42VordHfMKGBeyfUGkDEtLY',
    appId: '1:171608628367:web:620d672fed2240c288e4fa',
    messagingSenderId: '171608628367',
    projectId: 'notifications-16f19',
    authDomain: 'notifications-16f19.firebaseapp.com',
    storageBucket: 'notifications-16f19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUxBTWz_eRehwrTUlr1FUcTt0t1lhdhqA',
    appId: '1:171608628367:android:ac681fa15d8bdf8888e4fa',
    messagingSenderId: '171608628367',
    projectId: 'notifications-16f19',
    storageBucket: 'notifications-16f19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_kz8cd4VhKE3Qa4v34AZ8jXj9wmPRNQ0',
    appId: '1:171608628367:ios:ccd5d36fcb7899f388e4fa',
    messagingSenderId: '171608628367',
    projectId: 'notifications-16f19',
    storageBucket: 'notifications-16f19.appspot.com',
    iosClientId: '171608628367-pmqescfrki81fpr3begm8pbmlpb4pl6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelBooking',
  );
}
